<html>
<head>
<title>TestNG:  Surefire test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Surefire test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>26/0/0</td>
</tr><tr>
<td>Started on:</td><td>Mon Feb 25 17:43:20 IST 2019</td>
</tr>
<tr><td>Total time:</td><td>0 seconds (416 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.nuance.him.service.CustomerServiceImplTest.testAddCustomer()'><b>testAddCustomer</b><br>Test class: com.nuance.him.service.CustomerServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.CustomerServiceImplTest@5b275dab</td></tr>
<tr>
<td title='com.nuance.him.service.CustomerServiceImplTest.testAddCustomerException()'><b>testAddCustomerException</b><br>Test class: com.nuance.him.service.CustomerServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.CustomerServiceException: 
	at com.nuance.him.service.customer.CustomerServiceImpl.addCustomer(CustomerServiceImpl.java:42)
	at com.nuance.him.service.CustomerServiceImplTest.testAddCustomerException(CustomerServiceImplTest.java:82)
Caused by: com.nuance.him.dao.daoexception.CustomerDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace634540230", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace634540230'><pre>com.nuance.him.service.serviceexception.CustomerServiceException: 
	at com.nuance.him.service.customer.CustomerServiceImpl.addCustomer(CustomerServiceImpl.java:42)
	at com.nuance.him.service.CustomerServiceImplTest.testAddCustomerException(CustomerServiceImplTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.CustomerDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.CustomerServiceImplTest@5b275dab</td></tr>
<tr>
<td title='com.nuance.him.service.AccountServiceImplTest.testDepositException()'><b>testDepositException</b><br>Test class: com.nuance.him.service.AccountServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.AccountServiceException: 
	at com.nuance.him.service.account.AccountServiceImpl.getCurrentBalance(AccountServiceImpl.java:73)
	at com.nuance.him.service.account.AccountServiceImpl.depositeAmount(AccountServiceImpl.java:55)
	at com.nuance.him.service.AccountServiceImplTest.testDepositException(AccountServiceImplTest.java:148)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace715378067", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace715378067'><pre>com.nuance.him.service.serviceexception.AccountServiceException: 
	at com.nuance.him.service.account.AccountServiceImpl.getCurrentBalance(AccountServiceImpl.java:73)
	at com.nuance.him.service.account.AccountServiceImpl.depositeAmount(AccountServiceImpl.java:55)
	at com.nuance.him.service.AccountServiceImplTest.testDepositException(AccountServiceImplTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.AccountServiceImplTest@4501b7af</td></tr>
<tr>
<td title='com.nuance.him.service.AccountServiceImplTest.testDeposite()'><b>testDeposite</b><br>Test class: com.nuance.him.service.AccountServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.AccountServiceImplTest@4501b7af</td></tr>
<tr>
<td title='com.nuance.him.service.CustomerServiceImplTest.testDisplayCustomer()'><b>testDisplayCustomer</b><br>Test class: com.nuance.him.service.CustomerServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.CustomerServiceImplTest@5b275dab</td></tr>
<tr>
<td title='com.nuance.him.service.CustomerServiceImplTest.testDisplayCustomerException()'><b>testDisplayCustomerException</b><br>Test class: com.nuance.him.service.CustomerServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.CustomerServiceException: 
	at com.nuance.him.service.customer.CustomerServiceImpl.getAllCustomers(CustomerServiceImpl.java:52)
	at com.nuance.him.service.CustomerServiceImplTest.testDisplayCustomerException(CustomerServiceImplTest.java:112)
Caused by: com.nuance.him.dao.daoexception.CustomerDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1840976765", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1840976765'><pre>com.nuance.him.service.serviceexception.CustomerServiceException: 
	at com.nuance.him.service.customer.CustomerServiceImpl.getAllCustomers(CustomerServiceImpl.java:52)
	at com.nuance.him.service.CustomerServiceImplTest.testDisplayCustomerException(CustomerServiceImplTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.CustomerDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.CustomerServiceImplTest@5b275dab</td></tr>
<tr>
<td title='com.nuance.him.service.CustomerServiceImplTest.testFindCustomer()'><b>testFindCustomer</b><br>Test class: com.nuance.him.service.CustomerServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.CustomerServiceImplTest@5b275dab</td></tr>
<tr>
<td title='com.nuance.him.service.CustomerServiceImplTest.testFindCustomerException()'><b>testFindCustomerException</b><br>Test class: com.nuance.him.service.CustomerServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.CustomerServiceException: 
	at com.nuance.him.service.customer.CustomerServiceImpl.findCustomerById(CustomerServiceImpl.java:62)
	at com.nuance.him.service.CustomerServiceImplTest.testFindCustomerException(CustomerServiceImplTest.java:143)
Caused by: com.nuance.him.dao.daoexception.CustomerDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace222511810", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace222511810'><pre>com.nuance.him.service.serviceexception.CustomerServiceException: 
	at com.nuance.him.service.customer.CustomerServiceImpl.findCustomerById(CustomerServiceImpl.java:62)
	at com.nuance.him.service.CustomerServiceImplTest.testFindCustomerException(CustomerServiceImplTest.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.CustomerDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.CustomerServiceImplTest@5b275dab</td></tr>
<tr>
<td title='com.nuance.him.service.AccountServiceImplTest.testGetAccountDetail()'><b>testGetAccountDetail</b><br>Test class: com.nuance.him.service.AccountServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.AccountServiceImplTest@4501b7af</td></tr>
<tr>
<td title='com.nuance.him.service.AccountServiceImplTest.testGetAccountDetailException()'><b>testGetAccountDetailException</b><br>Test class: com.nuance.him.service.AccountServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.AccountServiceException: 
	at com.nuance.him.service.account.AccountServiceImpl.getAccountDetail(AccountServiceImpl.java:83)
	at com.nuance.him.service.AccountServiceImplTest.testGetAccountDetailException(AccountServiceImplTest.java:180)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace502800944", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace502800944'><pre>com.nuance.him.service.serviceexception.AccountServiceException: 
	at com.nuance.him.service.account.AccountServiceImpl.getAccountDetail(AccountServiceImpl.java:83)
	at com.nuance.him.service.AccountServiceImplTest.testGetAccountDetailException(AccountServiceImplTest.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.AccountServiceImplTest@4501b7af</td></tr>
<tr>
<td title='com.nuance.him.service.AccountServiceImplTest.testGetBalance()'><b>testGetBalance</b><br>Test class: com.nuance.him.service.AccountServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.AccountServiceImplTest@4501b7af</td></tr>
<tr>
<td title='com.nuance.him.service.AccountServiceImplTest.testGetBalanceException()'><b>testGetBalanceException</b><br>Test class: com.nuance.him.service.AccountServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.AccountServiceException: 
	at com.nuance.him.service.account.AccountServiceImpl.getCurrentBalance(AccountServiceImpl.java:73)
	at com.nuance.him.service.AccountServiceImplTest.testGetBalanceException(AccountServiceImplTest.java:114)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace260840925", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace260840925'><pre>com.nuance.him.service.serviceexception.AccountServiceException: 
	at com.nuance.him.service.account.AccountServiceImpl.getCurrentBalance(AccountServiceImpl.java:73)
	at com.nuance.him.service.AccountServiceImplTest.testGetBalanceException(AccountServiceImplTest.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.AccountServiceImplTest@4501b7af</td></tr>
<tr>
<td title='com.nuance.him.service.InterestServiceimplTest.testGetBalanceException()'><b>testGetBalanceException</b><br>Test class: com.nuance.him.service.InterestServiceimplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.InterestServiceException: 
	at com.nuance.him.service.account.InterestCalculatorServiceImpl.calculateMonthlyInterest(InterestCalculatorServiceImpl.java:40)
	at com.nuance.him.service.InterestServiceimplTest.testGetBalanceException(InterestServiceimplTest.java:73)
Caused by: com.nuance.him.dao.daoexception.InterestDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace536765369", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace536765369'><pre>com.nuance.him.service.serviceexception.InterestServiceException: 
	at com.nuance.him.service.account.InterestCalculatorServiceImpl.calculateMonthlyInterest(InterestCalculatorServiceImpl.java:40)
	at com.nuance.him.service.InterestServiceimplTest.testGetBalanceException(InterestServiceimplTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.InterestDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.InterestServiceimplTest@61832929</td></tr>
<tr>
<td title='com.nuance.him.service.InterestServiceimplTest.testInterestRateCalculator()'><b>testInterestRateCalculator</b><br>Test class: com.nuance.him.service.InterestServiceimplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.InterestServiceimplTest@61832929</td></tr>
<tr>
<td title='com.nuance.him.service.AtmServiceImplTest.testIsAtmAlreadyTaken()'><b>testIsAtmAlreadyTaken</b><br>Test class: com.nuance.him.service.AtmServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.AtmServiceImplTest@523884b2</td></tr>
<tr>
<td title='com.nuance.him.service.AtmServiceImplTest.testIsAtmAlreadyTakenException()'><b>testIsAtmAlreadyTakenException</b><br>Test class: com.nuance.him.service.AtmServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.AtmServiceException: 
	at com.nuance.him.service.atm.AtmServiceImpl.isAlreadyAtmTaken(AtmServiceImpl.java:70)
	at com.nuance.him.service.AtmServiceImplTest.testIsAtmAlreadyTakenException(AtmServiceImplTest.java:117)
Caused by: com.nuance.him.dao.daoexception.AtmDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace225472281", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace225472281'><pre>com.nuance.him.service.serviceexception.AtmServiceException: 
	at com.nuance.him.service.atm.AtmServiceImpl.isAlreadyAtmTaken(AtmServiceImpl.java:70)
	at com.nuance.him.service.AtmServiceImplTest.testIsAtmAlreadyTakenException(AtmServiceImplTest.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.AtmDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.AtmServiceImplTest@523884b2</td></tr>
<tr>
<td title='com.nuance.him.service.AtmServiceImplTest.testIssueAtm()'><b>testIssueAtm</b><br>Test class: com.nuance.him.service.AtmServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.AtmServiceImplTest@523884b2</td></tr>
<tr>
<td title='com.nuance.him.service.AtmServiceImplTest.testIssueAtmException()'><b>testIssueAtmException</b><br>Test class: com.nuance.him.service.AtmServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.AtmServiceException: 
	at com.nuance.him.service.atm.AtmServiceImpl.issueAtmCard(AtmServiceImpl.java:60)
	at com.nuance.him.service.AtmServiceImplTest.testIssueAtmException(AtmServiceImplTest.java:85)
Caused by: com.nuance.him.service.serviceexception.AtmAlreadyTakenException: Atm Already issued
	at com.nuance.him.service.atm.AtmServiceImpl.issueAtmCard(AtmServiceImpl.java:51)
	... 32 more
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace102617125", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace102617125'><pre>com.nuance.him.service.serviceexception.AtmServiceException: 
	at com.nuance.him.service.atm.AtmServiceImpl.issueAtmCard(AtmServiceImpl.java:60)
	at com.nuance.him.service.AtmServiceImplTest.testIssueAtmException(AtmServiceImplTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.service.serviceexception.AtmAlreadyTakenException: Atm Already issued
	at com.nuance.him.service.atm.AtmServiceImpl.issueAtmCard(AtmServiceImpl.java:51)
	... 32 more
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.AtmServiceImplTest@523884b2</td></tr>
<tr>
<td title='com.nuance.him.service.AccountServiceImplTest.testOpenAccount()'><b>testOpenAccount</b><br>Test class: com.nuance.him.service.AccountServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.AccountServiceImplTest@4501b7af</td></tr>
<tr>
<td title='com.nuance.him.service.AccountServiceImplTest.testOpenAccountException()'><b>testOpenAccountException</b><br>Test class: com.nuance.him.service.AccountServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.AccountServiceException: 
	at com.nuance.him.service.account.AccountServiceImpl.getAccountTypeId(AccountServiceImpl.java:115)
	at com.nuance.him.service.account.AccountServiceImpl.addAccount(AccountServiceImpl.java:44)
	at com.nuance.him.service.AccountServiceImplTest.testOpenAccountException(AccountServiceImplTest.java:82)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace6320204", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace6320204'><pre>com.nuance.him.service.serviceexception.AccountServiceException: 
	at com.nuance.him.service.account.AccountServiceImpl.getAccountTypeId(AccountServiceImpl.java:115)
	at com.nuance.him.service.account.AccountServiceImpl.addAccount(AccountServiceImpl.java:44)
	at com.nuance.him.service.AccountServiceImplTest.testOpenAccountException(AccountServiceImplTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.AccountServiceImplTest@4501b7af</td></tr>
<tr>
<td title='com.nuance.him.service.TransferAmountServiceImplTest.testTransactionHistory()'><b>testTransactionHistory</b><br>Test class: com.nuance.him.service.TransferAmountServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.TransferAmountServiceImplTest@29774679</td></tr>
<tr>
<td title='com.nuance.him.service.TransferAmountServiceImplTest.testTransactionHistoryException()'><b>testTransactionHistoryException</b><br>Test class: com.nuance.him.service.TransferAmountServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.TransferAmountServiceException: 
	at com.nuance.him.service.transaction.TransferAmountServiceImpl.getTransactionHistory(TransferAmountServiceImpl.java:75)
	at com.nuance.him.service.TransferAmountServiceImplTest.testTransactionHistoryException(TransferAmountServiceImplTest.java:107)
Caused by: com.nuance.him.dao.daoexception.TransferDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1556995360", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1556995360'><pre>com.nuance.him.service.serviceexception.TransferAmountServiceException: 
	at com.nuance.him.service.transaction.TransferAmountServiceImpl.getTransactionHistory(TransferAmountServiceImpl.java:75)
	at com.nuance.him.service.TransferAmountServiceImplTest.testTransactionHistoryException(TransferAmountServiceImplTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.TransferDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.TransferAmountServiceImplTest@29774679</td></tr>
<tr>
<td title='com.nuance.him.service.TransferAmountServiceImplTest.testTransferAmount()'><b>testTransferAmount</b><br>Test class: com.nuance.him.service.TransferAmountServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.TransferAmountServiceImplTest@29774679</td></tr>
<tr>
<td title='com.nuance.him.service.TransferAmountServiceImplTest.testTransferAmountException()'><b>testTransferAmountException</b><br>Test class: com.nuance.him.service.TransferAmountServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.TransferAmountServiceException: 
	at com.nuance.him.service.transaction.TransferAmountServiceImpl.transferAmount(TransferAmountServiceImpl.java:65)
	at com.nuance.him.service.TransferAmountServiceImplTest.testTransferAmountException(TransferAmountServiceImplTest.java:76)
Caused by: com.nuance.him.dao.daoexception.TransferDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1624820151", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1624820151'><pre>com.nuance.him.service.serviceexception.TransferAmountServiceException: 
	at com.nuance.him.service.transaction.TransferAmountServiceImpl.transferAmount(TransferAmountServiceImpl.java:65)
	at com.nuance.him.service.TransferAmountServiceImplTest.testTransferAmountException(TransferAmountServiceImplTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.TransferDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.TransferAmountServiceImplTest@29774679</td></tr>
<tr>
<td title='com.nuance.him.service.AccountServiceImplTest.testWithDrawAmountException()'><b>testWithDrawAmountException</b><br>Test class: com.nuance.him.service.AccountServiceImplTest</td>
<td><div><pre>com.nuance.him.service.serviceexception.AccountServiceException: 
	at com.nuance.him.service.account.AccountServiceImpl.getCurrentBalance(AccountServiceImpl.java:73)
	at com.nuance.him.service.AccountServiceImplTest.testWithDrawAmountException(AccountServiceImplTest.java:214)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
... Removed 31 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1978869058", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1978869058'><pre>com.nuance.him.service.serviceexception.AccountServiceException: 
	at com.nuance.him.service.account.AccountServiceImpl.getCurrentBalance(AccountServiceImpl.java:73)
	at com.nuance.him.service.AccountServiceImplTest.testWithDrawAmountException(AccountServiceImplTest.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
</pre></div></td>
<td>0</td>
<td>com.nuance.him.service.AccountServiceImplTest@4501b7af</td></tr>
<tr>
<td title='com.nuance.him.service.AccountServiceImplTest.testWithdraw()'><b>testWithdraw</b><br>Test class: com.nuance.him.service.AccountServiceImplTest</td>
<td></td>
<td>0</td>
<td>com.nuance.him.service.AccountServiceImplTest@4501b7af</td></tr>
</table><p>
</body>
</html>